export const GMS_CLASSES = [
  'Hero',
  'Paladin',
  'Dark Knight',
  'Arch Mage (Fire, Poison)',
  'Arch Mage (Ice, Lightning)',
  'Bishop',
  'Bowmaster',
  'Marksman',
  'Pathfinder',
  'Night Lord',
  'Shadower',
  'Dual Blade',
  'Buccaneer',
  'Corsair',
  'Cannoneer',
  'Dawn Warrior',
  'Blaze Wizard',
  'Wind Archer',
  'Night Walker',
  'Thunder Breaker',
  'Mihile',
  'Aran',
  'Evan',
  'Luminous',
  'Mercedes',
  'Phantom',
  'Shade',
  'Blaster',
  'Battle Mage',
  'Wild Hunter',
  'Mechanic',
  'Xenon',
  'Demon Slayer',
  'Demon Avenger',
  'Kaiser',
  'Angelic Buster',
  'Cadena',
  'Kain',
  'Adele',
  'Illium',
  'Khali',
  'Ark',
  'Hayato',
  'Kanna',
  'Hoyoung',
  'Lara',
  'Ren',
  'Lynn',
  'Mo Xuan',
  'Sia Astelle',
  'Zero',
  'Kinesis',
] as const;

export type GmsClass = (typeof GMS_CLASSES)[number];
